FROM node:alpine

ARG PORT

ENV MONGODB_URI {MONGODB_URI}
ENV CORS_ORIGIN {CORS_ORIGIN}
ENV ACCESS_TOKEN_SECRET {ACCESS_TOKEN_SECRET}
ENV ACCESS_TOKEN_EXPIRY {ACCESS_TOKEN_EXPIRY}
ENV REFRESH_TOKEN_SECRET {REFRESH_TOKEN_SECRET}
ENV REFRESH_TOKEN_EXPIRY {REFRESH_TOKEN_EXPIRY}
ENV NODE_ENV {NODE_ENV}

ENV CLOUDINARY_CLOUD_NAME {CLOUDINARY_CLOUD_NAME}
ENV CLOUDINARY_API_KEY {CLOUDINARY_API_KEY}
ENV CLOUDINARY_API_SECRET {CLOUDINARY_API_SECRET}

WORKDIR /usr/apps/cha-backend

COPY package.json .
COPY yarn.lock .

RUN yarn install --production=true

COPY . .

EXPOSE ${PORT}

CMD ["yarn", "start"]
